AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Auto Scaling Group with Apache and EBS

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro

  AmiId:
    Description: AMI ID (Amazon Linux 2 preferred)
    Type: AWS::EC2::Image::Id

  Subnet1:
    Description: Subnet ID for launching EC2 instances
    Type: AWS::EC2::Subnet::Id

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      VpcId: vpc-0dd065dae0bc4f0a2  # ✅ REQUIRED: VPC ID must be explicitly provided
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        ImageId: !Ref AmiId
        SecurityGroupIds:
          - !Ref WebServerSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            echo "<h1>Hello from CloudFormation Auto Scaling</h1>" > /var/www/html/index.html
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 8
              DeleteOnTermination: true
              VolumeType: gp2
          - DeviceName: /dev/sdf
            Ebs:
              VolumeSize: 20
              DeleteOnTermination: true
              VolumeType: gp2

  WebServerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      VPCZoneIdentifier:
        - !Ref Subnet1
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: AutoScalingWebServer
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroup:
    Description: Auto Scaling Group name
    Value: !Ref WebServerASG